import '../styles/globals.scss'
import 'bootstrap/dist/css/bootstrap.min.css'
import Head from 'next/head'
import type { AppProps } from 'next/app'

import { Global, css } from '@emotion/react'
import { UserProvider } from '@auth0/nextjs-auth0'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <div className="container">
      <Head>
        <title>Auth nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <UserProvider>
        <Global
          styles={css`
            *,
            *::after,
            *::before {
              box-sizing: border-box;
              font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
              padding: 0;
              margin: 0;
            }

            a {
              text-decoration: none;
            }

            ul {
              list-style: none;
            }
          `}
        />
        <Component {...pageProps} />
      </UserProvider>
    </div>
  )
}

export default MyApp
